version: '3'

services:
  db:
    image: mysql:5.7 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
     - "3306:3306" 
    volumes: 
     - ./db:/var/lib/mysql
  web:
    build: .
    # command: bash -c "rm -f /tmp/pids/server pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - ./bundler_gems:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment: 
      DB_USER: root
      DB_NAME: noteapp
      DB_PASSWORD: password
      DB_HOST: db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# volumes:
#   mysql:
#   bundler_gems: